apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: VictoriaMetrics
    orgId: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    orgId: 1
    url: http://victoriametrics:8481/select/0/prometheus
    uid: victoria_metrics
    basicAuth: false
    isDefault: true
    jsonData:
       graphiteVersion: "1.1"
       tlsAuth: false
       tlsAuthWithCACert: false
    secureJsonData:
      tlsCACert: "..."
      tlsClientCert: "..."
      tlsClientKey: "..."
    version: 1
    editable: false

  - name: Loki
    type: loki
    access: proxy
    uid: loki
    url: http://loki:3100
    jsonData:
      maxLines: 1000