{
 "title": "Service: harp-daemon",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Pod Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(kube_pod_container_status_restarts_total{container=\"harp-daemon\"}[1m]))"
    }
   ]
  },
  {
   "title": "Service Errors Logs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by (service, severity, namespace) (count_over_time({service=\"harp-daemon\",severity=~\"error|critical\"}[1m]))"
    }
   ]
  },
  {
   "title": "Service Errors Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "{service=\"harp-daemon\",severity=~\"error|critical\"}"
    }
   ]
  },
  {
   "title": "Actual CPU Usage per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{exported_container=\"harp-daemon\",resource=\"cpu\"})",
     "legendFormat": "limits_cpu_cores"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"harp-daemon\"}[1m])) by (pod)"
    }
   ]
  },
  {
   "title": "AVG Service CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg(rate(container_cpu_usage_seconds_total{container=\"harp-daemon\"}[1m])) / avg(kube_pod_container_resource_limits{container=\"harp-daemon\",resource=\"cpu\"})) * 100"
    }
   ]
  },
  {
   "title": "Total Service CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"harp-daemon\"}[1m]))"
    }
   ]
  },
  {
   "title": "Actual Memory Usage per pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{exported_container=\"harp-daemon\",resource=\"memory\"})",
     "legendFormat": "limits_memory"
    },
    {
     "expr": "sum(container_memory_max_usage_bytes{container=\"harp-daemon\"}) by (pod)"
    }
   ]
  },
  {
   "title": "AVG Memory Service Usage %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\navg(container_memory_max_usage_bytes{container=\"harp-daemon\"}) /\navg(kube_pod_container_resource_limits{container=\"harp-daemon\",resource=\"memory\"})\n) * 100\n\n\n",
     "legendFormat": "limits_memory"
    }
   ]
  },
  {
   "title": "Total Memory Service Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_max_usage_bytes{container=\"harp-daemon\"})\n\n\n",
     "legendFormat": "limits_memory"
    }
   ]
  },
  { "title": "General Service metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "TOTAL: Notifications count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "rate(total_notification_processor_latency_seconds_count{service=\"harp-daemon\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TOTAL: Notifications latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(total_notification_processor_latency_seconds_sum{service=\"harp-daemon\"}[1m]) /\nrate(total_notification_processor_latency_seconds_count{service=\"harp-daemon\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "UI: Notifications count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(ui_create_notification_latency_seconds_count{service=\"harp-daemon\"}[1m]))",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(ui_update_notification_latency_seconds_count{service=\"harp-daemon\"}[1m]))",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(ui_resubmit_notification_latency_seconds_count{service=\"harp-daemon\"}[1m]))",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(ui_close_notification_latency_seconds_count{service=\"harp-daemon\"}[1m]))",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "UI: Notifications latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(ui_create_notification_latency_seconds_sum{service=\"harp-daemon\"}[1m])) /\nsum(rate(ui_create_notification_latency_seconds_count{service=\"harp-daemon\"}[1m]))",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(ui_update_notification_latency_seconds_sum{service=\"harp-daemon\"}[1m])) /\nsum(rate(ui_update_notification_latency_seconds_count{service=\"harp-daemon\"}[1m]))",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(ui_resubmit_notification_latency_seconds_sum{service=\"harp-daemon\"}[1m])) /\nsum(rate(ui_resubmit_notification_latency_seconds_count{service=\"harp-daemon\"}[1m]))",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(ui_close_notification_latency_seconds_sum{service=\"harp-daemon\"}[1m])) /\nsum(rate(ui_close_notification_latency_seconds_count{service=\"harp-daemon\"}[1m]))",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "EMAIL: Notifications count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(email_create_notification_latency_seconds_count{service=\"harp-daemon\"}[1m]))",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(email_update_notification_latency_seconds_count{service=\"harp-daemon\"}[1m]))",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(email_resubmit_notification_latency_seconds_count{service=\"harp-daemon\"}[1m]))",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(email_close_notification_latency_seconds_count{service=\"harp-daemon\"}[1m]))",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "EMAIL: Notifications latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(email_create_notification_latency_seconds_sum{service=\"harp-daemon\"}[1m])) /\nsum(rate(email_create_notification_latency_seconds_count{service=\"harp-daemon\"}[1m]))",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(email_update_notification_latency_seconds_sum{service=\"harp-daemon\"}[1m])) /\nsum(rate(email_update_notification_latency_seconds_count{service=\"harp-daemon\"}[1m]))",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(email_resubmit_notification_latency_seconds_sum{service=\"harp-daemon\"}[1m])) /\nsum(rate(email_resubmit_notification_latency_seconds_count{service=\"harp-daemon\"}[1m]))",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(email_close_notification_latency_seconds_sum{service=\"harp-daemon\"}[1m])) /\nsum(rate(email_close_notification_latency_seconds_count{service=\"harp-daemon\"}[1m]))",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "JIRA: Notifications count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(jira_create_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(jira_update_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(jira_resubmit_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(jira_close_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "JIRA: Notifications latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(jira_create_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(jira_create_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(jira_update_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(jira_update_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(jira_resubmit_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(jira_resubmit_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(jira_close_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(jira_close_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "PD: Notifications count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(pd_create_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(pd_update_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(pd_resubmit_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(pd_close_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "PD: Notifications latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(pd_create_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(pd_create_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(pd_update_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(pd_update_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(pd_resubmit_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(pd_resubmit_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(pd_close_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(pd_close_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "SKYPE: Notifications count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(skype_create_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(skype_update_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(skype_resubmit_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(skype_close_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "SKYPE: Notifications latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(skype_create_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(skype_create_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(skype_update_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(skype_update_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(skype_resubmit_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(skype_resubmit_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(skype_close_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(skype_close_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "SMS: Notifications count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(sms_create_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(sms_update_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(sms_resubmit_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(sms_close_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "SMS: Notifications latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(sms_create_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(sms_create_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(sms_update_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(sms_update_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(sms_resubmit_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(sms_resubmit_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(sms_close_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(sms_close_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "TEAMS: Notifications count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(teams_create_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(teams_update_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(teams_resubmit_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(teams_close_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "TEAMS: Notifications latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(teams_create_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(teams_create_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(teams_update_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(teams_update_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(teams_resubmit_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(teams_resubmit_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(teams_close_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(teams_close_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "TELEGRAM: Notifications count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(telegram_create_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(telegram_update_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(telegram_resubmit_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(telegram_close_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "TELEGRAM: Notifications latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(telegram_create_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(telegram_create_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(telegram_update_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(telegram_update_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(telegram_resubmit_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(telegram_resubmit_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(telegram_close_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(telegram_close_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "VOICE: Notifications count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(voice_create_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(voice_update_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(voice_resubmit_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(voice_close_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "VOICE: Notifications latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(voice_create_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(voice_create_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(voice_update_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(voice_update_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(voice_resubmit_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(voice_resubmit_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(voice_close_notification_latency_seconds_sum{service=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(voice_close_notification_latency_seconds_count{service=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "Flask Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests count  =! 200",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flask_http_request_duration_seconds_count{status!=\"200\", service=\"harp-daemon\"}[1m])",
       "legendFormat": "{{pod}}: {{method}} - {{path}}"
      }
     ]
    },
    {
     "title": "GET: Requests count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flask_http_request_duration_seconds_count{method=\"GET\",status=\"200\", service=\"harp-daemon\"}[1m:15s])",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "GET: Requests latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(flask_http_request_duration_seconds_sum{method=\"GET\",status=\"200\", service=\"harp-daemon\"}[1m]) /\nrate(flask_http_request_duration_seconds_count{method=\"GET\",status=\"200\", service=\"harp-daemon\"}[1m])",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "POST: Requests count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flask_http_request_duration_seconds_count{method=\"POST\",status=\"200\", service=\"harp-daemon\"}[1m:15s])",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "POST: Requests latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(flask_http_request_duration_seconds_sum{method=\"POST\",status=\"200\", service=\"harp-daemon\"}[1m]) /\nrate(flask_http_request_duration_seconds_count{method=\"POST\",status=\"200\", service=\"harp-daemon\"}[1m])",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "PUT: Requests count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flask_http_request_duration_seconds_count{method=\"PUT\",status=\"200\", service=\"harp-daemon\"}[1m:15s])",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "PUT: Requests latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(flask_http_request_duration_seconds_sum{method=\"PUT\",status=\"200\", service=\"harp-daemon\"}[1m]) /\nrate(flask_http_request_duration_seconds_count{method=\"PUT\",status=\"200\", service=\"harp-daemon\"}[1m])",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "DELETE: Requests count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flask_http_request_duration_seconds_count{method=\"DELETE\",status=\"200\", service=\"harp-daemon\"}[1m:15s])",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "DELETE: Requests latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(flask_http_request_duration_seconds_sum{method=\"DELETE\",status=\"200\", service=\"harp-daemon\"}[1m]) /\nrate(flask_http_request_duration_seconds_count{method=\"DELETE\",status=\"200\", service=\"harp-daemon\"}[1m])",
       "legendFormat": "{{path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Notification Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true,
   "panels": [
    {
     "title": "ALERT_RESUBMIT_PROCESSOR_COUNT",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "rate(alert_resubmit_processor_latency_seconds_count{service=\"harp-daemon\"}[$Interval]) * 60",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ALERT_RESUBMIT_PROCESSOR_LATENCY",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(alert_resubmit_processor_latency_seconds_sum{service=\"harp-daemon\"}[$Interval]) * 60 /\nrate(alert_resubmit_processor_latency_seconds_count{service=\"harp-daemon\"}[$Interval]) * 60",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GRAPH_RENDER_PROCESSOR_COUNT",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "rate(graph_render_processor_latency_seconds_count{service=\"harp-daemon\"}[$Interval]) * 60",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GRAPH_RENDER_PROCESSOR_LATENCY",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(graph_render_processor_latency_seconds_sum{service=\"harp-daemon\"}[$Interval]) * 60 /\nrate(graph_render_processor_latency_seconds_count{service=\"harp-daemon\"}[$Interval]) * 60",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ALERT_ASSIGN_PROCESSOR_COUNT",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "rate(alert_assign_processor_latency_seconds_count{service=\"harp-daemon\"}[$Interval]) * 60",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ALERT_ASSIGN_PROCESSOR_LATENCY",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(alert_assign_processor_latency_seconds_sum{service=\"harp-daemon\"}[$Interval]) * 60 /\nrate(alert_assign_processor_latency_seconds_count{service=\"harp-daemon\"}[$Interval]) * 60",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ENV_DICT_UPDATE_PROCESSOR_COUNT",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "rate(env_dict_update_processor_latency_seconds_count{service=\"harp-daemon\"}[$Interval]) * 60",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ENV_DICT_UPDATE_PROCESSOR_LATENCY",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(env_dict_update_processor_latency_seconds_sum{service=\"harp-daemon\"}[$Interval]) * 60 /\nrate(env_dict_update_processor_latency_seconds_count{service=\"harp-daemon\"}[$Interval]) * 60",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}