{
 "title": "Service: harp-bridge",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Pod Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(kube_pod_container_status_restarts_total{container=\"harp-bridge\"}[1m]))"
    }
   ]
  },
  {
   "title": "Service Errors Logs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by (service, severity) (count_over_time({job=\"harp-bridge\",severity=~\"error|critical|warning\"}[1m]))"
    }
   ]
  },
  {
   "title": "Service Errors Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "{job=\"harp-bridge\",severity=~\"error|critical|warning\"}"
    }
   ]
  },
  {
   "title": "Actual CPU Usage per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{exported_container=\"harp-bridge\",resource=\"cpu\"})",
     "legendFormat": "limits_cpu_cores"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"harp-bridge\"}[1m])) by (pod)"
    }
   ]
  },
  {
   "title": "AVG Service CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg(rate(container_cpu_usage_seconds_total{container=\"harp-bridge\"}[1m])) / avg(kube_pod_container_resource_limits{container=\"harp-bridge\",resource=\"cpu\"})) * 100"
    }
   ]
  },
  {
   "title": "Total Service CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"harp-bridge\"}[1m]))"
    }
   ]
  },
  {
   "title": "Actual Memory Usage per pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{exported_container=\"harp-bridge\",resource=\"memory\"})",
     "legendFormat": "limits_memory"
    },
    {
     "expr": "sum(container_memory_max_usage_bytes{container=\"harp-bridge\"}) by (pod)"
    }
   ]
  },
  {
   "title": "AVG Memory Service Usage %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\navg(container_memory_max_usage_bytes{container=\"harp-bridge\"}) /\navg(kube_pod_container_resource_limits{container=\"harp-bridge\",resource=\"memory\"})\n) * 100\n\n\n",
     "legendFormat": "limits_memory"
    }
   ]
  },
  {
   "title": "Total Memory Service Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_max_usage_bytes{container=\"harp-bridge\"})\n\n\n",
     "legendFormat": "limits_memory"
    }
   ]
  },
  {
   "title": "Service metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aerospike read count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "idelta(aerospike_read_latency_seconds_count{job=\"harp-bridge\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Aerospike read latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(aerospike_read_latency_seconds_sum{job=\"harp-bridge\"}[1m]) /\nrate(aerospike_read_latency_seconds_count{job=\"harp-bridge\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Client connect count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "idelta(client_connect_latency_seconds_count{job=\"harp-bridge\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Client connect latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(client_connect_latency_seconds_sum{job=\"harp-bridge\"}[1m]) /\nrate(client_connect_latency_seconds_count{job=\"harp-bridge\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Client disconnect count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "idelta(client_disconnect_latency_seconds_count{job=\"harp-bridge\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Client disconnect latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(client_disconnect_latency_seconds_sum{job=\"harp-bridge\"}[1m]) /\nrate(client_disconnect_latency_seconds_count{job=\"harp-bridge\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Client update_filter count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "idelta(client_update_filter_latency_seconds_count{job=\"harp-bridge\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Client update_filter latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(client_update_filter_latency_seconds_sum{job=\"harp-bridge\"}[1m]) /\nrate(client_update_filter_latency_seconds_count{job=\"harp-bridge\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Client update_room count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "idelta(client_update_room_latency_seconds_count{job=\"harp-bridge\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Client update_room latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(client_update_room_latency_seconds_sum{job=\"harp-bridge\"}[1m]) /\nrate(client_update_room_latency_seconds_count{job=\"harp-bridge\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Flask Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Requests count  =! 200",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{status!=\"200\", job=\"harp-bridge\"}[1m:15s])",
     "legendFormat": "{{pod}}: {{method}} - {{path}}"
    }
   ]
  },
  {
   "title": "GET: Requests count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{method=\"GET\",status=\"200\", job=\"harp-bridge\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "GET: Requests latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{method=\"GET\",status=\"200\", job=\"harp-bridge\"}[1m]) /\nrate(flask_http_request_duration_seconds_count{method=\"GET\",status=\"200\", job=\"harp-bridge\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "POST: Requests count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{method=\"POST\",status=\"200\", job=\"harp-bridge\"}[1m:15s])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "POST: Requests latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{method=\"POST\",status=\"200\", job=\"harp-bridge\"}[1m]) /\nrate(flask_http_request_duration_seconds_count{method=\"POST\",status=\"200\", job=\"harp-bridge\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "PUT: Requests count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{method=\"PUT\",status=\"200\", job=\"harp-bridge\"}[1m:15s])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "PUT: Requests latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{method=\"PUT\",status=\"200\", job=\"harp-bridge\"}[1m]) /\nrate(flask_http_request_duration_seconds_count{method=\"PUT\",status=\"200\", job=\"harp-bridge\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "DELETE: Requests count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{method=\"DELETE\",status=\"200\", job=\"harp-bridge\"}[1m:15s])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "DELETE: Requests latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{method=\"DELETE\",status=\"200\", job=\"harp-bridge\"}[1m]) /\nrate(flask_http_request_duration_seconds_count{method=\"DELETE\",status=\"200\", job=\"harp-bridge\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}