{
 "title": "Service: harp-collectors",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Pod Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(kube_pod_container_status_restarts_total{container=\"harp-collectors\"}[1m]))"
    }
   ]
  },
  {
   "title": "Service Errors Logs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by (service, severity) (count_over_time({job=\"harp-collectors\",severity=~\"error|critical|warning\"}[1m]))"
    }
   ]
  },
  {
   "title": "Service Errors Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "{job=\"harp-collectors\",severity=~\"error|critical|warning\"}"
    }
   ]
  },
  {
   "title": "Actual CPU Usage per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{container=\"harp-collectors\",resource=\"cpu\"})",
     "legendFormat": "limits_cpu_cores"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"harp-collectors\"}[1m])) by (pod)"
    }
   ]
  },
  {
   "title": "AVG Service CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg(rate(container_cpu_usage_seconds_total{container=\"harp-collectors\"}[1m])) / avg(kube_pod_container_resource_limits{container=\"harp-collectors\",resource=\"cpu\"})) * 100"
    }
   ]
  },
  {
   "title": "Total Service CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"harp-collectors\"}[1m]))"
    }
   ]
  },
  {
   "title": "Actual Memory Usage per pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{exported_container=\"harp-collectors\",resource=\"memory\"})",
     "legendFormat": "limits_memory"
    },
    {
     "expr": "sum(container_memory_max_usage_bytes{container=\"harp-collectors\"}) by (pod)"
    }
   ]
  },
  {
   "title": "AVG Memory Service Usage %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\navg(container_memory_max_usage_bytes{container=\"harp-collectors\"}) /\navg(kube_pod_container_resource_limits{container=\"harp-collectors\",resource=\"memory\"})\n) * 100\n\n\n",
     "legendFormat": "limits_memory"
    }
   ]
  },
  {
   "title": "Total Memory Service Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_max_usage_bytes{container=\"harp-collectors\"})\n\n\n",
     "legendFormat": "limits_memory"
    }
   ]
  },
  { "title": "Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Requests count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum by (handler, namespace) (rate(http_requests_total{method=\"POST\",job=\"harp-collectors\"}[1m]))",
     "legendFormat": "{{namespace}}: {{handler}}"
    }
   ]
  },
  {
   "title": "Requests latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (handler, namespace) (rate(http_request_duration_seconds_sum{job=\"harp-collectors\"}[1m])) /\nsum by (handler, namespace) (rate(http_request_duration_seconds_count{job=\"harp-collectors\"}[1m]))",
     "legendFormat": "{{namespace}}: {{handler}}"
    }
   ]
  },
  {
   "title": "Flask Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests count  =! 200",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(starlette_responses_total{method=\"POST\",namespace=\"btigroup\",job=\"harp-collectors\",status_code!=\"200\"}[1m])",
       "legendFormat": "{{pod}}: {{method}} - {{path}}"
      }
     ]
    },
    {
     "title": "GET: Requests count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (path_template) (rate(starlette_requests_processing_time_seconds_count{method=\"GET\",job=\"harp-collectors\"}[1m]))",
       "legendFormat": "{{path_template}}"
      }
     ]
    },
    {
     "title": "GET: Requests latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (path_template) (rate(starlette_requests_processing_time_seconds_sum{method=\"GET\",job=\"harp-collectors\"}[1m])) /\nsum by (path_template) (rate(starlette_requests_processing_time_seconds_count{method=\"GET\",job=\"harp-collectors\"}[1m]))",
       "legendFormat": "{{path_template}}"
      }
     ]
    },
    {
     "title": "POST: Requests count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (path_template) (rate(starlette_requests_processing_time_seconds_count{method=\"POST\",job=\"harp-collectors\"}[1m]))",
       "legendFormat": "{{path_template}}"
      }
     ]
    },
    {
     "title": "POST: Requests latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (path_template) (rate(starlette_requests_processing_time_seconds_sum{method=\"POST\",job=\"harp-collectors\"}[1m])) /\nsum by (path_template) (rate(starlette_requests_processing_time_seconds_count{method=\"POST\",job=\"harp-collectors\"}[1m]))",
       "legendFormat": "{{path_template}}"
      }
     ]
    },
    {
     "title": "PUT: Requests count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (path_template) (rate(starlette_requests_processing_time_seconds_count{method=\"PUT\",job=\"harp-collectors\"}[1m]))",
       "legendFormat": "{{path_template}}"
      }
     ]
    },
    {
     "title": "PUT: Requests latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (path_template) (rate(starlette_requests_processing_time_seconds_sum{method=\"PUT\",job=\"harp-collectors\"}[1m])) /\nsum by (path_template) (rate(starlette_requests_processing_time_seconds_count{method=\"PUT\",job=\"harp-collectors\"}[1m]))",
       "legendFormat": "{{path_template}}"
      }
     ]
    },
    {
     "title": "DELETE: Requests count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (path_template) (rate(starlette_requests_processing_time_seconds_count{method=\"DELETE\",job=\"harp-collectors\"}[1m]))",
       "legendFormat": "{{path_template}}"
      }
     ]
    },
    {
     "title": "DELETE: Requests latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (path_template) (rate(starlette_requests_processing_time_seconds_sum{method=\"DELETE\",job=\"harp-collectors\"}[1m])) /\nsum by (path_template) (rate(starlette_requests_processing_time_seconds_count{method=\"DELETE\",job=\"harp-collectors\"}[1m]))",
       "legendFormat": "{{path_template}}"
      }
     ]
    }
   ]
  }
 ]
}